Task-1
Here we need to create a one dimensional random numpy array of size 10.
Firstly i have imported the numpy as np. In the second line I have initialized a variable named random_array where I will be storing the randomly geenrated array. np.random.randit is the function for generating random integer values in an array. My array will contain integers upto 50 and the array size will be 10. Finally i have printed the array.



In [3]:
import numpy as np
random_array = np.random.randint(50, size = 10)
print(random_array)

[23  6 24 24 12  1 38 39 23 46]


Task -2 Here we need tp+o create a two dimensional numpy array of size 7x6 and reshape it to 3x14 array. In the 2nd line the np.arange(42) creates an one dimensional array from 0 to 41 the using reshape I have reshaped it into a 7/6 2D array and stored it in the initial_array. Then finally I have reshaped the initial array to a 3/14 2D array and stored in the final array.

In [6]:
import numpy as np
initial_array = np.arange(42).reshape(7,6)
final_array = initial_array.reshape(3,14)
print("initial array: ")
print(initial_array)
print("\nfinal array")
print(final_array)

initial array: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]]

final array
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]]


Task -3 We have to create an array and extract all the odd numbers from it. [array([0,1,2,3,4,5,6,7,8,9])]. new_array%2!=0 This creates a boolean mask where the odd numbers are set to True and the evens are False. We are applying this mask to new_array and storing the True values in the odd_array.

In [11]:
import numpy as np
new_array = np.arange(10)
odd_array = new_array[new_array%2!=0]

print(odd_array)

[1 3 5 7 9]


Task-4 We have to replace all the odd numbers in the previous array with -1.
==> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]). We are applying the boolean mask in the new_array as the previous task. As it returns the odd values as True then we have set the value -1 to those indexes.  

In [12]:
import numpy as np
new_array = np.arange(10)
new_array[new_array%2!=0] = -1
print(new_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Task-5:
I have made a copy of the previous array to a new one. Then I did exactly the same as task 4 and then printed both of the arrays.

In [15]:
import numpy as np
old_array = np.arange(10)
new_array = old_array.copy()
new_array[new_array%2!=0] = -1
print(old_array)
print(new_array)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Task-6:
np.where function finds the position where both of the array element matches. But it returns the result as tuples where each element of the tuple represents a dimension of the input arrays. So if we print the 0th element of result tuple then we can get the output as array.

In [17]:
import numpy as np
array_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
array_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
result = np.where(array_a == array_b)
print(result[0])

[1 3 5 7]


Task - 7:
I have used boolean indexing to find the numbers between 5 and 10. The result array returns the numbers where the conditions meet.

In [18]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = a[(a >= 5) & (a <= 10)]
print(result)

[ 6  9 10]


Task-**8** : I have reshaped the arrays in 5/2 matrix. The to merge vertically I have used concatenate and axis=0 which means vertical and axis =1 means horizontal.

In [20]:
import numpy as np
zero_vector = np.zeros(10)
ones_vector = np.ones(10)
zero_vector = zero_vector.reshape(5,2)
ones_vector = ones_vector.reshape(5,2)
merged_vertically = np.concatenate((zero_vector, ones_vector), axis=0)
merged_horizontally = np.concatenate((zero_vector, ones_vector), axis=1)
print("Merged Vertically:")
print(merged_vertically)

print("\nMerged Horizontally:")
print(merged_horizontally)


Merged Vertically:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Merged Horizontally:
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


Task -9 : np.random.rand() function generates random numbers between 0 and 1. If we dont use randint it will give all fractional values.

In [24]:
import numpy as np
random_array = np.random.rand(5, 4)

print(random_array)

[[0.98837384 0.10204481 0.20887676 0.16130952]
 [0.65310833 0.2532916  0.46631077 0.24442559]
 [0.15896958 0.11037514 0.65632959 0.13818295]
 [0.19658236 0.36872517 0.82099323 0.09710128]
 [0.83794491 0.09609841 0.97645947 0.4686512 ]]


Task-10 : x array is the sample data with features. y generates an array with only 0 and 1 and the array size will be the sample size.

In [25]:
import numpy as np

n_samples = 5
n_features = 4
x = np.random.rand(n_samples, n_features)
y = np.random.randint(0, 2, n_samples)

print('x =', x)
print('y =', y)

x = [[0.97676109 0.60484552 0.73926358 0.03918779]
 [0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798318 0.41426299 0.0641475  0.69247212]
 [0.56660145 0.26538949 0.52324805 0.09394051]
 [0.5759465  0.9292962  0.31856895 0.66741038]]
y = [1 0 0 0 0]


Task-11: here we need to find the subset of x which matches with the target class value.

In [28]:
import numpy as np
def extract_subset(x, y, y0):
  subset_x = x[y==y0]
  return subset_x

n_samples = 5
n_features = 4
x = np.random.rand(n_samples, n_features)

y = np.random.randint(0, 2, n_samples)

target_class = 0 #y0 in function

subset_x = extract_subset(x, y, target_class)

print(x)
print(y)
print(subset_x)

[[0.22126269 0.1412639  0.09725993 0.98404224]
 [0.26034093 0.53702252 0.44792617 0.09956909]
 [0.35231166 0.46924917 0.84114013 0.90464774]
 [0.03755938 0.50831545 0.16684751 0.77905102]
 [0.8649333  0.41139672 0.13997259 0.03322239]]
[1 1 1 1 0]
[[0.8649333  0.41139672 0.13997259 0.03322239]]


Task-12:
imported the iris datasets from sklearn. Here I have imported the number as iris.data and text labels as target class.

In [31]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
target_class = iris.target_names
print("Data:\n", X)
print("\nText Labels:\n", target_class)

Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9

Task-13:
numpy functions are used for finding out the mean, median and standard deviation. Also added the summary of the whole dataset which includes mean median and std deviation.

In [37]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
first_column = X[:, 0]
mean_value = np.mean(first_column)
median_value = np.median(first_column)
std_dev = np.std(first_column)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev)

summary_dataset_mean = np.mean(X)
print("Summary Mean:",summary_dataset_mean)
summary_dataset_median = np.median(X)
print("Summary Median:",summary_dataset_median)
summary_dataset_std_deviation = np.std(X)
print("Summary Standard Deviation:", summary_dataset_std_deviation )

Mean: 5.843333333333334
Median: 5.8
Standard Deviation: 0.8253012917851409
Summary Mean: 3.4644999999999997
Summary Median: 3.2
Summary Standard Deviation: 1.9738430577598278
